platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'ubiQVue Cam.xcodeproj'

pod 'CocoaAsyncSocket', '~> 7.3'

#target "ubiQVue Cam" do
#
#end
#
#target "ubiQVue CamTests" do
#
#end
