platform :ios, "7.0"

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'VULCAM eye.xcodeproj'

pod 'CocoaAsyncSocket', :git => 'git@github.com:BitKaitsu/CocoaAsyncSocket', :branch => 'master'
pod 'ios-ntp', :git => 'git@github.com:BitKaitsu/ios-ntp', :branch => 'master'

#target "VULCAM eye" do
#
#end
#
#target "vulCam eyeTests" do
#
#end
